name: Deploy the Beta MYR Docker Image

on:
  repository_dispatch:
    types: [update_dev]

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    container:
      image: docker
    steps:
      - uses: actions/checkout@v2
      - name: Log into Quay
        run: docker login quay.io -u umlecg+myr_bot -p ${{ secrets.QUAY_BOT_PASSWORD }}
      - name: Build the docker image
        run: docker build -t quay.io/umlecg/myr:dev -f Dockerfile.dev .
      - name: Deploy the docker image
        run: docker push quay.io/umlecg/myr:dev